name: CI
on:
    - push
    - pull_request
jobs:
    test:
        name: Tests on node.js ${{ matrix.node-version }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version:
                    - 18
                    - 17
                    - 16
                    - 14
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: wget https://github.com/w3c/xsdtests/archive/master.zip -O /tmp/xsdtests.zip
            - run: unzip /tmp/xsdtests.zip
            - run: npm install
            - run: npm test -- --verbose false
              env:
                  XML_SCHEMA_TESTS_PATH: ./xsdtests-master
